service: ProCoders

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  environment:
    STRIPE_SECRET_KEY: ${file(./.env.${opt:stage}.yml):STRIPE_SECRET_KEY}

functions:
  checkForFinishedPayments:
    handler: handler.call
    events:
      - http:
          path: /
          method: post